checks:
  jira_pr_link:
    auto_comment_pr_link: false
  jira_status:
    auto_in_review_status_change: false
  jira_description: false
  jira_component: false
  jira_fix_version: false
  branch_name: false
  commit_message: false
edits:
  auto_closed_status_change: false